# Generated by Django 2.0.9 on 2018-10-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol', models.IntegerField()),
                ('earths_date', models.DateField()),
                ('air_temp_max', models.IntegerField()),
                ('air_temp_min', models.IntegerField()),
                ('ground_temp_max', models.IntegerField()),
                ('ground_temp_min', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('wind_speed', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('sunrise_time', models.TimeField()),
                ('sunset_time', models.TimeField()),
                ('atmospheric_opacity', models.CharField(max_length=64)),
                ('radiation_level', models.CharField(max_length=128)),
            ],
        ),
    ]
