# Generated by Django 2.0.9 on 2018-10-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sol',
            name='humidity',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sol',
            name='wind_speed',
            field=models.CharField(max_length=64),
        ),
    ]
